# Preparacion del conjunto de datos (Silver -> Gold con Spark)

Objetivo: preparar el dataset etiquetado de mood para entrenamiento y los catalogos de tracks/lyrics para clasificacion y recomendacion.

Alcance: limpieza, consistencia, tratamiento de outliers, features derivadas, escalado y split.

Fuente unica: capa Silver en S3. Procesamiento completo con Apache Spark.

Salida: datasets preparados en S3 (Gold), incluyendo el nuevo dataset con lyrics.

In [1]:
import os
import sys
import shutil
from pathlib import Path
from typing import Dict, List, Tuple

import boto3
import numpy as np
import pandas as pd
from pyspark.sql import functions as F

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
from src.config import load_settings
from src.spark.session import build_spark
from src.aws.athena_catalog import AthenaTableSpec, register_parquet_tables, run_validation_queries

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 120)

settings = load_settings()
spark = build_spark("music-recommender-data-prep")

# Temporary local folder for Silver data downloaded from S3
local_silver_base = settings.project_root / "data_lake" / "tmp_silver"
local_silver_mood = local_silver_base / "mood_dataset"
local_silver_tracks = local_silver_base / "tracks_dataset"
local_silver_lyrics = local_silver_base / "lyrics_dataset"
local_silver_mood.mkdir(parents=True, exist_ok=True)
local_silver_tracks.mkdir(parents=True, exist_ok=True)
local_silver_lyrics.mkdir(parents=True, exist_ok=True)

s3 = boto3.client("s3", region_name=settings.aws_region)

def download_prefix(bucket: str, prefix: str, local_dir: Path) -> None:
    if local_dir.exists():
        shutil.rmtree(local_dir)
    local_dir.mkdir(parents=True, exist_ok=True)
    paginator = s3.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for obj in page.get("Contents", []):
            key = obj["Key"]
            if key.endswith("/"):
                continue
            rel = key[len(prefix):]
            if not rel:
                continue
            target = local_dir / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            s3.download_file(bucket, key, str(target))

settings

Settings(project_root=WindowsPath('C:/Users/losal/Desktop/CursoEspecializacion/TFG/Music_Mood_Activity_Recommender'), data_dir=WindowsPath('C:/Users/losal/Desktop/CursoEspecializacion/TFG/Music_Mood_Activity_Recommender/datasets'), local_lake_dir=WindowsPath('C:/Users/losal/Desktop/CursoEspecializacion/TFG/Music_Mood_Activity_Recommender/data_lake'), bucket_name='music-recommender-lake-807744154206', aws_region='us-east-1', s3_endpoint_url=None, use_s3=True, kafka_bootstrap_servers='localhost:9092', kafka_group_id='music-recommender-pipeline', max_rows_per_dataset=None, producer_batch_size=5000, producer_batch_delay_seconds=0.1, consumer_timeout_seconds=None, mongo_uri='mongodb+srv://othmanerizqy:othmanerizqy123@music-recommender.fmdmupd.mongodb.net/?appName=music-recommender', mongo_database='music_recommender', rds_host='music-recommender.cjaaeyokabhb.us-east-1.rds.amazonaws.com', rds_port=3306, rds_database='music_recommender', rds_user='admin', rds_password='12345678', athena_database='music_recommender_lake', athena_results_s3='s3://music-recommender-lake-807744154206/athena/results/', athena_workgroup='primary', lambda_function_name='music-recommender-pipeline-metadata', lambda_invocation_type='Event')

In [2]:
silver_prefix_mood = "silver/mood_dataset/"
silver_prefix_tracks = "silver/tracks_dataset/"
silver_prefix_lyrics = "silver/lyrics_dataset/"
download_prefix(settings.bucket_name, silver_prefix_mood, local_silver_mood)
download_prefix(settings.bucket_name, silver_prefix_tracks, local_silver_tracks)
download_prefix(settings.bucket_name, silver_prefix_lyrics, local_silver_lyrics)

mood_silver = spark.read.parquet(str(local_silver_mood))
tracks_silver = spark.read.parquet(str(local_silver_tracks))
lyrics_silver = spark.read.parquet(str(local_silver_lyrics))

print("Silver mood:", f"s3://{settings.bucket_name}/{silver_prefix_mood}")
print("Silver tracks:", f"s3://{settings.bucket_name}/{silver_prefix_tracks}")
print("Silver lyrics:", f"s3://{settings.bucket_name}/{silver_prefix_lyrics}")
print("Local temp (mood):", local_silver_mood)
print("Local temp (tracks):", local_silver_tracks)
print("Local temp (lyrics):", local_silver_lyrics)
print("Rows mood:", mood_silver.count())
print("Rows tracks:", tracks_silver.count())
print("Rows lyrics:", lyrics_silver.count())

Silver mood: s3://music-recommender-lake-807744154206/silver/mood_dataset/
Silver tracks: s3://music-recommender-lake-807744154206/silver/tracks_dataset/
Silver lyrics: s3://music-recommender-lake-807744154206/silver/lyrics_dataset/
Local temp (mood): C:\Users\losal\Desktop\CursoEspecializacion\TFG\Music_Mood_Activity_Recommender\data_lake\tmp_silver\mood_dataset
Local temp (tracks): C:\Users\losal\Desktop\CursoEspecializacion\TFG\Music_Mood_Activity_Recommender\data_lake\tmp_silver\tracks_dataset
Local temp (lyrics): C:\Users\losal\Desktop\CursoEspecializacion\TFG\Music_Mood_Activity_Recommender\data_lake\tmp_silver\lyrics_dataset
Rows mood: 277938
Rows tracks: 89740
Rows lyrics: 955320

## 1. Comprension general (mood)
Se valida estructura, tipos y nulos del dataset etiquetado.

In [3]:
def overview_spark(df, name: str, preview_rows: int = 3):
    print(name, "rows", df.count())
    display(df.limit(preview_rows).toPandas())
    df.printSchema()
    null_exprs = [F.mean(F.col(c).isNull().cast("double")).alias(c) for c in df.columns]
    nulls = df.select(*null_exprs).toPandas().T.rename(columns={0: "null_pct"})
    display(nulls.sort_values("null_pct", ascending=False).head(10))

overview_spark(mood_silver, "mood_silver")
overview_spark(tracks_silver, "tracks_silver")
overview_spark(lyrics_silver, "lyrics_silver")

mood_silver rows 277938

,acousticness,danceability,duration_ms,energy,instrumentalness,mood_label,liveness,loudness,spec_rate,speechiness,tempo,uri,valence
0,0.000601,0.478,214627,0.903,0.000000,2,0.1240,-5.350,6.522944e-07,0.1400,173.967,spotify:track:7M7VUNhN51Fjsu58dLv0EY,0.736
1,0.000157,0.589,266791,0.906,0.017400,2,0.3210,-5.190,1.795413e-07,0.0479,130.918,spotify:track:5XuzKbpYnjE6Th8Zqq6iBC,0.514
2,0.014900,0.577,208827,0.833,0.000011,2,0.0274,-5.206,2.379960e-07,0.0497,125.221,spotify:track:4CmYkMfs8y54aBnQlINBKJ,0.768

root
 |-- acousticness: double (nullable = true)
 |-- danceability: double (nullable = true)
 |-- duration_ms: long (nullable = true)
 |-- energy: double (nullable = true)
 |-- instrumentalness: double (nullable = true)
 |-- mood_label: integer (nullable = true)
 |-- liveness: double (nullable = true)
 |-- loudness: double (nullable = true)
 |-- spec_rate: double (nullable = true)
 |-- speechiness: double (nullable = true)
 |-- tempo: double (nullable = true)
 |-- uri: string (nullable = true)
 |-- valence: double (nullable = true)

                  null_pct
acousticness           0.0
danceability           0.0
duration_ms            0.0
energy                 0.0
instrumentalness       0.0
mood_label             0.0
liveness               0.0
loudness               0.0
spec_rate              0.0
speechiness            0.0

tracks_silver rows 89740

,acousticness,album_name,artists,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo,time_signature,track_genre,track_id,track_name,valence
0,0.0757,Lolly,Rill,0.910,160725,0.374,True,0.003010,8,0.154,-9.844,0,44,0.1990,104.042,4,german,0000vdREvCVMxbQTkS888c,Lolly,0.432
1,0.3160,New RnB,Pink Sweat$;Kirby,0.613,176320,0.471,False,0.000001,1,0.117,-6.644,0,0,0.1070,143.064,4,chill,001APMDOl3qtx1526T11n1,Better,0.406
2,0.0051,Find Me (Remixes),Sigma;Birdy,0.415,252342,0.888,False,0.002000,5,0.186,-2.544,0,20,0.0685,174.986,4,drum-and-bass,002uYDBLOvJz21C4FuArDS,Find Me - Sigma VIP Remix,0.146

root
 |-- acousticness: double (nullable = true)
 |-- album_name: string (nullable = true)
 |-- artists: string (nullable = true)
 |-- danceability: double (nullable = true)
 |-- duration_ms: integer (nullable = true)
 |-- energy: double (nullable = true)
 |-- explicit: boolean (nullable = true)
 |-- instrumentalness: double (nullable = true)
 |-- key: integer (nullable = true)
 |-- liveness: double (nullable = true)
 |-- loudness: double (nullable = true)
 |-- mode: integer (nullable = true)
 |-- popularity: integer (nullable = true)
 |-- speechiness: double (nullable = true)
 |-- tempo: double (nullable = true)
 |-- time_signature: integer (nullable = true)
 |-- track_genre: string (nullable = true)
 |-- track_id: string (nullable = true)
 |-- track_name: string (nullable = true)
 |-- valence: double (nullable = true)

                  null_pct
acousticness           0.0
album_name             0.0
artists                0.0
danceability           0.0
duration_ms            0.0
energy                 0.0
explicit               0.0
instrumentalness       0.0
key                    0.0
liveness               0.0

lyrics_silver rows 955320

,acousticness,album_name,artists,danceability,duration_ms,energy,track_id,instrumentalness,key,liveness,loudness,lyrics,mode,track_name,speechiness,tempo,valence
0,0.0244,A Midnight Dreary,LorD and Master,0.648,246750,0.838,000JJAuQyGXgrkPCaiZhu5,0.000387,2,0.1440,-3.260,Any other day would be OK Any other day you'd ...,0,Any Other Day,0.0568,119.985,0.848
1,0.6350,Extraña,Addys Mercedes,0.974,205253,0.545,000TVLMODj7klbrl92vucb,0.000453,4,0.0877,-9.896,"Piden, arroz para comer agua, del rio pa' bebe...",0,Nada,0.0606,123.999,0.897
2,0.5230,The Complete Collection...And Then Some,Barry Manilow,0.313,292000,0.944,000rSvYFyzERahYbYaXHnV,0.002730,4,0.9840,-8.894,"Christy wants a millionaire, a miracle in the ...",1,Riders To The Stars - Digitally Remastered: 1992,0.2320,145.568,0.526

root
 |-- acousticness: double (nullable = true)
 |-- album_name: string (nullable = true)
 |-- artists: string (nullable = true)
 |-- danceability: double (nullable = true)
 |-- duration_ms: integer (nullable = true)
 |-- energy: double (nullable = true)
 |-- track_id: string (nullable = true)
 |-- instrumentalness: double (nullable = true)
 |-- key: integer (nullable = true)
 |-- liveness: double (nullable = true)
 |-- loudness: double (nullable = true)
 |-- lyrics: string (nullable = true)
 |-- mode: integer (nullable = true)
 |-- track_name: string (nullable = true)
 |-- speechiness: double (nullable = true)
 |-- tempo: double (nullable = true)
 |-- valence: double (nullable = true)

                  null_pct
acousticness           0.0
album_name             0.0
artists                0.0
danceability           0.0
duration_ms            0.0
energy                 0.0
track_id               0.0
instrumentalness       0.0
key                    0.0
liveness               0.0

## 2. Seleccion e integracion de variables base

Se unifican los tres datasets Silver mediante un esquema acustico comun. Mood aporta el target supervisado, Tracks aporta catalogo musical y Lyrics aporta senales textuales. Tambien se comprueba compatibilidad de columnas, duplicados y posibles conflictos entre fuentes antes de pasar a Gold.

In [4]:
MOOD_FEATURES = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence", "loudness", "tempo", "spec_rate", "duration_ms"
]
TRACKS_FEATURES = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence", "loudness", "tempo", "duration_ms"
]
LYRICS_FEATURES = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence", "loudness", "tempo", "duration_ms"
]

mood_features = [c for c in MOOD_FEATURES if c in mood_silver.columns]
tracks_features = [c for c in TRACKS_FEATURES if c in tracks_silver.columns]
lyrics_features = [c for c in LYRICS_FEATURES if c in lyrics_silver.columns]
shared_features = [c for c in mood_features if c in tracks_features]
lyrics_shared_features = [c for c in mood_features if c in lyrics_features]
if "mood_label" not in mood_silver.columns:
    raise ValueError("mood_label no existe en Silver")
if "track_id" not in tracks_silver.columns:
    raise ValueError("track_id no existe en Silver tracks")
if "track_id" not in lyrics_silver.columns:
    raise ValueError("track_id no existe en Silver lyrics")

mood_base = mood_silver.select(["mood_label", *shared_features])
tracks_base = tracks_silver.select(["track_id", *shared_features])
lyrics_base = lyrics_silver.select(["track_id", *lyrics_shared_features, "lyrics"])

# Normalizar tipos numericos y eliminar columnas no necesarias para entrenamiento acustico.
for col in shared_features:
    mood_base = mood_base.withColumn(col, F.col(col).cast("double"))
    tracks_base = tracks_base.withColumn(col, F.col(col).cast("double"))
for col in lyrics_shared_features:
    lyrics_base = lyrics_base.withColumn(col, F.col(col).cast("double"))
mood_base = mood_base.withColumn("mood_label", F.col("mood_label").cast("int"))
lyrics_base = lyrics_base.withColumn("lyrics", F.coalesce(F.col("lyrics"), F.lit("")))

lyrics_base

DataFrame[track_id: string, danceability: double, energy: double, speechiness: double, acousticness: double, instrumentalness: double, liveness: double, valence: double, loudness: double, tempo: double, duration_ms: double, lyrics: string]

### 2.1 Validacion de integracion, duplicados y conflictos entre fuentes

Esta celda deja evidencia de la unificacion de multiples datasets: columnas compartidas, duplicados por identificador y conflictos de metadatos cuando un mismo `track_id` aparece en Tracks y Lyrics con informacion distinta.

In [5]:
def count_duplicates(df, subset: List[str]) -> int:
    return df.count() - df.dropDuplicates(subset).count()

integration_report = pd.DataFrame([
    {
        "dataset": "mood",
        "rows": mood_silver.count(),
        "shared_audio_features": len(shared_features),
        "duplicate_rows": count_duplicates(mood_silver.select(["mood_label", *shared_features]), ["mood_label", *shared_features]),
        "duplicate_track_id": None,
    },
    {
        "dataset": "tracks",
        "rows": tracks_silver.count(),
        "shared_audio_features": len(shared_features),
        "duplicate_rows": count_duplicates(tracks_silver.select(["track_id", *shared_features]), ["track_id", *shared_features]),
        "duplicate_track_id": count_duplicates(tracks_silver, ["track_id"]),
    },
    {
        "dataset": "lyrics",
        "rows": lyrics_silver.count(),
        "shared_audio_features": len(lyrics_shared_features),
        "duplicate_rows": count_duplicates(lyrics_silver.select(["track_id", *lyrics_shared_features]), ["track_id", *lyrics_shared_features]),
        "duplicate_track_id": count_duplicates(lyrics_silver, ["track_id"]),
    },
])
display(integration_report)

metadata_conflict_cols = [c for c in ["track_name", "artists", "album_name", "track_genre"] if c in tracks_silver.columns and c in lyrics_silver.columns]
if metadata_conflict_cols:
    joined_meta = tracks_silver.select("track_id", *[F.col(c).alias(f"tracks_{c}") for c in metadata_conflict_cols]).join(
        lyrics_silver.select("track_id", *[F.col(c).alias(f"lyrics_{c}") for c in metadata_conflict_cols]),
        on="track_id",
        how="inner",
    )
    conflict_exprs = [
        F.sum((F.col(f"tracks_{c}") != F.col(f"lyrics_{c}")).cast("int")).alias(c)
        for c in metadata_conflict_cols
    ]
    display(joined_meta.select(*conflict_exprs).toPandas().T.rename(columns={0: "metadata_conflicts"}))
else:
    print("No hay columnas de metadatos comparables entre Tracks y Lyrics.")

  dataset    rows  shared_audio_features  duplicate_rows  duplicate_track_id
0    mood  277938                     10            1678                 NaN
1  tracks   89740                     10               0                 0.0
2  lyrics  955320                     10               0                 0.0

            metadata_conflicts
track_name                 478
artists                   1860
album_name                3850

### 2.2 Justificacion de variables conservadas o descartadas

La seleccion prioriza variables acusticas numericas compatibles entre fuentes. Como apoyo, se calcula la correlacion absoluta con `mood_label`; las columnas no seleccionadas se descartan por identificador, texto libre, metadato no numerico o falta de compatibilidad entre datasets.

In [6]:
mood_corr_pdf = mood_base.select(["mood_label", *shared_features]).toPandas()
correlation_justification = (
    mood_corr_pdf.corr(numeric_only=True)["mood_label"]
    .drop("mood_label")
    .abs()
    .sort_values(ascending=False)
    .reset_index()
    .rename(columns={"index": "feature", "mood_label": "abs_corr_with_mood"})
)
display(correlation_justification)

excluded_columns = sorted(set(mood_silver.columns) - set(["mood_label", *shared_features]))
exclusion_reasons = pd.DataFrame({
    "column": excluded_columns,
    "reason": [
        "identificador/metadato o columna no compatible con el esquema acustico comun"
        for _ in excluded_columns
    ],
})
display(exclusion_reasons.head(30))

            feature  abs_corr_with_mood
0  instrumentalness            0.541494
1          loudness            0.309437
2      danceability            0.229390
3           valence            0.182134
4       duration_ms            0.114558
5      acousticness            0.053265
6            energy            0.048570
7          liveness            0.019369
8       speechiness            0.006543
9             tempo            0.004499

      column                                             reason
0  spec_rate  identificador/metadato o columna no compatible...
1        uri  identificador/metadato o columna no compatible...

## 3. Limpieza: nulos e inconsistencias
Se corrigen tipos y se eliminan filas con nulos con medianas.

In [ ]:
import pyspark.sql.functions as F

# Mood: eliminar filas sin target
mood_clean = mood_base.filter(F.col("mood_label").isNotNull())
mood_clean = mood_clean.dropDuplicates(["mood_label", *shared_features])

# Si una misma combinacion acustica aparece con etiquetas distintas, se conserva la etiqueta mayoritaria.
feature_window_cols = [F.col(c) for c in shared_features]
conflict_counts = (
    mood_clean.groupBy(*shared_features)
    .agg(F.countDistinct("mood_label").alias("label_count"))
    .filter(F.col("label_count") > 1)
    .count()
)

if conflict_counts:
    majority_labels = (
        mood_clean.groupBy(*shared_features, "mood_label")
        .count()
        .orderBy(*shared_features, F.desc("count"), "mood_label")
        .dropDuplicates(shared_features)
        .select(*shared_features, "mood_label")
    )
    mood_clean = majority_labels

print("Conflictos de etiqueta resueltos en mood:", conflict_counts)

# Tracks: eliminar filas sin track_id y duplicados por track_id
tracks_clean = tracks_base.filter(F.col("track_id").isNotNull()).dropDuplicates(["track_id"])

# Lyrics: eliminar filas sin track_id, duplicados y mantener lyrics como texto limpio
lyrics_clean = lyrics_base.filter(F.col("track_id").isNotNull()).dropDuplicates(["track_id"])
lyrics_clean = lyrics_clean.withColumn("lyrics", F.trim(F.regexp_replace(F.col("lyrics"), r"\s+", " ")))

print("Rows mood after cleaning:", mood_clean.count())
print("Rows tracks after cleaning:", tracks_clean.count())
print("Rows lyrics after cleaning:", lyrics_clean.count())

Conflictos de etiqueta resueltos en mood: 0
Rows mood after cleaning: 276260
Rows tracks after cleaning: 89740
Rows lyrics after cleaning: 955320

## 4. Outliers
Se aplica clipping IQR por feature para reducir extremos sin borrar registros.

In [ ]:
from typing import List
import pyspark.sql.functions as F

# 1. Definimos las columnas protegidas de rango 0-1.
# Tienen demasiada asimetría legítima y no sufren de outliers infinitos.
NATURAL_BOUNDED_FEATURES = {
    "danceability",
    "energy",
    "speechiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "valence"
}

def clip_outliers_iqr(df, cols: List[str]):
    # Filtramos la lista: solo aplicamos IQR a variables no acotadas (tempo, loudness, duration_ms)
    cols_to_process = [col for col in cols if col not in NATURAL_BOUNDED_FEATURES]
    
    # Si tras el filtro no quedan columnas físicas en la lista recibida, devolvemos el df intacto
    if not cols_to_process:
        return df

    for col in cols_to_process:
        q1 = df.approxQuantile(col, [0.25], 0.001)[0]
        q3 = df.approxQuantile(col, [0.75], 0.001)[0]
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        
        df = df.withColumn(
            col, 
            F.when(F.col(col) < lower, lower)
             .when(F.col(col) > upper, upper)
             .otherwise(F.col(col))
        )
    return df

# Las llamadas se quedan exactamente igual, la función ya sabe qué filtrar internamente
mood_clipped = clip_outliers_iqr(mood_clean, shared_features)
tracks_clipped = clip_outliers_iqr(tracks_clean, shared_features)
lyrics_clipped = clip_outliers_iqr(lyrics_clean, lyrics_shared_features)

lyrics_clipped

DataFrame[track_id: string, danceability: double, energy: double, speechiness: double, acousticness: double, instrumentalness: double, liveness: double, valence: double, loudness: double, tempo: double, duration_ms: double, lyrics: string]

## 5. Ingenieria de features
Se mantiene el esquema acustico compatible para el modelo y se anaden senales textuales compactas derivadas de lyrics.

In [ ]:
import pyspark.sql.functions as F
from typing import List

def add_audio_engineered_features(df, cols: List[str]):
    result = df
    if "energy" in cols and "valence" in cols:
        result = result.withColumn("energy_valence_interaction", F.col("energy") * F.col("valence"))
        result = result.withColumn("energy_squared", F.pow(F.col("energy"), F.lit(2.0)))
        result = result.withColumn(
            "energy_bucket",
            F.when(F.col("energy") < 0.33, F.lit("low"))
            .when(F.col("energy") < 0.66, F.lit("mid"))
            .otherwise(F.lit("high")),
        )
        for bucket in ["low", "mid", "high"]:
            result = result.withColumn(f"energy_bucket_{bucket}", (F.col("energy_bucket") == bucket).cast("double"))
        result = result.drop("energy_bucket")
        
    if "valence" in cols:
        result = result.withColumn(
            "valence_bucket",
            F.when(F.col("valence") < 0.33, F.lit("low"))
            .when(F.col("valence") < 0.66, F.lit("mid"))
            .otherwise(F.lit("high")),
        )
        for bucket in ["low", "mid", "high"]:
            result = result.withColumn(f"valence_bucket_{bucket}", (F.col("valence_bucket") == bucket).cast("double"))
        result = result.drop("valence_bucket")
        
    if "tempo" in cols:
        result = result.withColumn("tempo_log1p", F.log1p(F.greatest(F.col("tempo"), F.lit(0.0))))
        
    if "duration_ms" in cols:
        result = result.withColumn("duration_sqrt", F.sqrt(F.greatest(F.col("duration_ms"), F.lit(0.0))))
        
    if "acousticness" in cols and "instrumentalness" in cols:
        result = result.withColumn("acoustic_instrumental_mix", F.col("acousticness") * F.col("instrumentalness"))
        
    return result

# 1. Aplicar features de audio
mood_fe = add_audio_engineered_features(mood_clean, shared_features)
tracks_fe = add_audio_engineered_features(tracks_clean, shared_features)
lyrics_fe = add_audio_engineered_features(lyrics_clean, lyrics_shared_features)

# 2. Definición de diccionarios semánticos profundos (Inglés + Español)
# Se usan raíces o palabras completas que evocan el sentimiento.

LEXICON_SAD = [
    # INGLÉS
    # Emoción/Dolor:
    "cry", "tear", "lonely", "alone", "hurt", "broken", "pain", "miss", "goodbye", 
    "sorrow", "grief", "regret", "ache", "despair", "numb", "gloom", "misery", 
    "weep", "mourn", "tragedy", "bleak", "heavy", "beg",
    # Metáforas/Naturaleza oscura:
    "shadow", "cold", "empty", "fade", "drown", "ash", "bleed", "darkness", 
    "ghost", "shatter", "abyss", "winter", "wither", "scar", "sink", "ruin", "grave",
    
    # ESPAÑOL
    # Emoción/Dolor:
    "triste", "llorar", "lagrima", "solo", "sola", "dolor", "adios", "pena", 
    "luto", "recuerdo", "amargo", "sufrir", "lamento", "rogar", "suplicar", 
    "cruel", "llanto", "culpa", "vacio",
    # Metáforas/Naturaleza oscura:
    "sombra", "frio", "desvanecer", "ahogar", "ceniza", "sangrar", "oscuridad", 
    "fantasma", "cicatriz", "abismo", "invierno", "marchito", "gris", "herida", 
    "hundir", "hielo", "morir", "perder", "nublado", "pesado", "ruina"
]

LEXICON_HAPPY = [
    # INGLÉS
    # Emoción/Celebración:
    "happy", "smile", "party", "joy", "dance", "celebrate", "laugh", "cheer", 
    "delight", "sweet", "freedom", "free", "thrill", "together", "glory", "wonder",
    # Luz/Ascensión/Vitalidad:
    "sun", "bright", "shine", "gold", "soar", "alive", "bloom", "paradise", 
    "glow", "magic", "sparkle", "heaven", "fly", "warm", "sunny", "dawn", 
    "miracle", "beautiful", "rise", "higher",
    
    # ESPAÑOL
    # Emoción/Celebración:
    "feliz", "sonrisa", "fiesta", "alegria", "bailar", "celebrar", "juntos", 
    "reir", "dulce", "beso", "maravilla", "libertad", "cantar", "gozo", 
    "disfrutar", "encanto", "sonreir",
    # Luz/Ascensión/Vitalidad:
    "sol", "brillar", "oro", "volar", "vivo", "viva", "florecer", "destello", 
    "paraiso", "vibrar", "resplandor", "magia", "cielo", "calor", "luz", 
    "amanecer", "milagro", "primavera", "brillo", "ascender"
]

LEXICON_ENERGETIC = [
    # INGLÉS
    # Fuerza/Agresión/Impacto:
    "fight", "wild", "break", "scream", "pulse", "rush", "explode", "roar", 
    "beast", "crash", "smash", "boom", "riot", "rebel", "kick", "punch", 
    "weapon", "force", "power", "shock", "pump", "monster", "shout", "hard", "hit",
    # Velocidad/Fuego/Volumen:
    "run", "fire", "jump", "move", "tonight", "loud", "thunder", "blood", 
    "sweat", "voltage", "engine", "ignite", "burn", "speed", "fast", 
    "hurricane", "tornado", "electric", "bass", "beat",
    
    # ESPAÑOL
    # Fuerza/Agresión/Impacto:
    "luchar", "saltar", "romper", "gritar", "pulso", "estallar", "rugir", 
    "bestia", "chocar", "golpe", "bomba", "rebelde", "furia", "rabia", 
    "fuerza", "poder", "empujar", "duro", "salvaje", "golpear", "monstruo",
    # Velocidad/Fuego/Volumen:
    "correr", "fuego", "mover", "noche", "trueno", "sangre", "sudor", 
    "adrenalina", "voltaje", "motor", "encender", "quemar", "velocidad", 
    "rapido", "huracan", "electrico", "ritmo"
]

LEXICON_CALM = [
    # INGLÉS
    # Relajación/Silencio:
    "peace", "sleep", "dream", "quiet", "soft", "slow", "breathe", "calm", 
    "whisper", "stillness", "chill", "relax", "rest", "lullaby", "hush", 
    "ease", "harmony", "serene", "soothe", "breath",
    # Naturaleza suave/Flotar:
    "ocean", "float", "tide", "drift", "twilight", "star", "forest", "refuge", 
    "meadow", "gently", "smooth", "moon", "breeze", "melt", "lake", "sunset",
    
    # ESPAÑOL
    # Relajación/Silencio:
    "paz", "dormir", "sueno", "silencio", "suave", "lento", "respirar", "calma", 
    "quietud", "relajar", "descanso", "pausa", "sereno", "armonia", "suspirar", 
    "acariciar", "meditar", "cuna", "tranquilo", "alivio",
    # Naturaleza suave/Flotar:
    "oceano", "flotar", "susurro", "marea", "deriva", "atardecer", "estrella", 
    "bosque", "refugio", "prado", "liso", "luna", "brisa", "lago", "ocaso"
]

# Unir las listas en un string de regex formateado: r"\b(palabra1|palabra2)\b"
regex_sad = r"\b(" + "|".join(LEXICON_SAD) + r")\b"
regex_happy = r"\b(" + "|".join(LEXICON_HAPPY) + r")\b"
regex_energetic = r"\b(" + "|".join(LEXICON_ENERGETIC) + r")\b"
regex_calm = r"\b(" + "|".join(LEXICON_CALM) + r")\b"

# 3. Extraer features léxicas
lyrics_fe = (
    lyrics_fe
    .withColumn("lyrics_length", F.length(F.col("lyrics")))
    .withColumn("lyrics_word_count", F.size(F.split(F.trim(F.col("lyrics")), r"\s+")))
    .withColumn("lyrics_sad_terms", F.size(F.regexp_extract_all(F.lower(F.col("lyrics")), F.lit(regex_sad), 1)))
    .withColumn("lyrics_happy_terms", F.size(F.regexp_extract_all(F.lower(F.col("lyrics")), F.lit(regex_happy), 1)))
    .withColumn("lyrics_energetic_terms", F.size(F.regexp_extract_all(F.lower(F.col("lyrics")), F.lit(regex_energetic), 1)))
    .withColumn("lyrics_calm_terms", F.size(F.regexp_extract_all(F.lower(F.col("lyrics")), F.lit(regex_calm), 1)))
)

# 4. Calcular los ratios de aparición (frecuencia normalizada)
for mood in ["sad", "happy", "energetic", "calm"]:
    lyrics_fe = lyrics_fe.withColumn(
        f"lyrics_{mood}_lexicon_rate",
        F.col(f"lyrics_{mood}_terms") / F.greatest(F.col("lyrics_word_count"), F.lit(1)),
    )

# 5. Limpieza de columnas temporales y texto bruto
lyrics_fe = lyrics_fe.drop("lyrics", "lyrics_sad_terms", "lyrics_happy_terms", "lyrics_energetic_terms", "lyrics_calm_terms")

print("Mood features finales:", [c for c in mood_fe.columns if c != "mood_label"])

Mood features finales: ['danceability', 'energy', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness', 'tempo', 'duration_ms', 'energy_valence_interaction', 'energy_squared', 'energy_bucket_low', 'energy_bucket_mid', 'energy_bucket_high', 'valence_bucket_low', 'valence_bucket_mid', 'valence_bucket_high', 'tempo_log1p', 'duration_sqrt', 'acoustic_instrumental_mix']

## 6. Escalado
Se estandarizan variables numericas con z-score usando estadisticas del dataset.

In [10]:
feature_cols = [c for c in mood_fe.columns if c != "mood_label"]

# Compute mean/std for scaling (from mood)
stats_rows = []
stats_map = {}
for col in feature_cols:
    row = mood_fe.agg(
        F.mean(F.col(col)).alias("mean"),
        F.stddev(F.col(col)).alias("std"),
    ).collect()[0]
    mean_val = row["mean"]
    std_val = row["std"] or 1.0
    stats_rows.append({"feature": col, "mean": float(mean_val), "std": float(std_val)})
    stats_map[col] = (mean_val, std_val)
    mood_fe = mood_fe.withColumn(col, (F.col(col) - F.lit(mean_val)) / F.lit(std_val))

mood_scaled = mood_fe
scaler_stats = pd.DataFrame(stats_rows)
scaler_stats.head()

            feature      mean       std
0      danceability  0.552521  0.188906
1            energy  0.556614  0.279694
2       speechiness  0.066054  0.041655
3      acousticness  0.386906  0.364564
4  instrumentalness  0.255386  0.373908

In [11]:
# Apply the same scaling to tracks and lyrics (only shared acoustic features)
tracks_scaled = tracks_fe
for col, (mean_val, std_val) in stats_map.items():
    if col in tracks_scaled.columns:
        tracks_scaled = tracks_scaled.withColumn(col, (F.col(col) - F.lit(mean_val)) / F.lit(std_val))

lyrics_scaled = lyrics_fe
for col, (mean_val, std_val) in stats_map.items():
    if col in lyrics_scaled.columns:
        lyrics_scaled = lyrics_scaled.withColumn(col, (F.col(col) - F.lit(mean_val)) / F.lit(std_val))

lyrics_scaled

DataFrame[track_id: string, danceability: double, energy: double, speechiness: double, acousticness: double, instrumentalness: double, liveness: double, valence: double, loudness: double, tempo: double, duration_ms: double, energy_valence_interaction: double, energy_squared: double, energy_bucket_low: double, energy_bucket_mid: double, energy_bucket_high: double, valence_bucket_low: double, valence_bucket_mid: double, valence_bucket_high: double, tempo_log1p: double, duration_sqrt: double, acoustic_instrumental_mix: double, lyrics_length: int, lyrics_word_count: int, lyrics_sad_lexicon_rate: double, lyrics_happy_lexicon_rate: double, lyrics_energetic_lexicon_rate: double, lyrics_calm_lexicon_rate: double]

## 7. Split train/test
Split estratificado 80/20 por `mood_label`.

In [12]:
labels = [row[0] for row in mood_scaled.select("mood_label").distinct().collect()]
train_parts = []
test_parts = []
for label in labels:
    subset = mood_scaled.filter(F.col("mood_label") == label)
    train_part, test_part = subset.randomSplit([0.8, 0.2], seed=42)
    train_parts.append(train_part)
    test_parts.append(test_part)

train_df = train_parts[0]
for part in train_parts[1:]:
    train_df = train_df.unionByName(part)
test_df = test_parts[0]
for part in test_parts[1:]:
    test_df = test_df.unionByName(part)

print("Train rows:", train_df.count(), "Test rows:", test_df.count())
train_df.groupBy("mood_label").count().show()
test_df.groupBy("mood_label").count().show()

Train rows: 221591 Test rows: 54669
+----------+-----+
|mood_label|count|
+----------+-----+
|         3|33892|
|         0|65482|
|         1|84720|
|         2|37497|
+----------+-----+

+----------+-----+
|mood_label|count|
+----------+-----+
|         3| 8296|
|         0|16146|
|         1|21008|
|         2| 9219|
+----------+-----+

## 8. Guardado en Gold (S3)
Se escriben train/test, estadisticas de escalado y catalogos preparados de tracks y lyrics en S3 Gold.

In [13]:
gold_local = settings.project_root / "data_lake" / "tmp_gold" / "mood_prepared"
tracks_local = settings.project_root / "data_lake" / "tmp_gold" / "tracks_prepared"
lyrics_local = settings.project_root / "data_lake" / "tmp_gold" / "lyrics_prepared"
gold_tracks_local = settings.project_root / "data_lake" / "gold" / "tracks_dataset"
gold_lyrics_local = settings.project_root / "data_lake" / "gold" / "lyrics_dataset"
for path in [gold_local, tracks_local, lyrics_local, gold_tracks_local, gold_lyrics_local]:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)

train_local = gold_local / "train"
test_local = gold_local / "test"
scaler_local = gold_local / "scaler_stats"
tracks_out_local = tracks_local / "full"
lyrics_out_local = lyrics_local / "full"

train_df.write.mode("overwrite").parquet(str(train_local))
test_df.write.mode("overwrite").parquet(str(test_local))

# Guardar scaler_stats sin usar Spark (evita fallos del worker).
scaler_local.mkdir(parents=True, exist_ok=True)
scaler_file = scaler_local / "scaler_stats.parquet"
try:
    scaler_stats.fillna(0).to_parquet(scaler_file, index=False)
except Exception:
    scaler_file = scaler_local / "scaler_stats.csv"
    scaler_stats.fillna(0).to_csv(scaler_file, index=False)

tracks_scaled.write.mode("overwrite").parquet(str(tracks_out_local))
lyrics_scaled.write.mode("overwrite").parquet(str(lyrics_out_local))

# Guardar metadata de tracks y lyrics para el recomendador.
metadata_cols = [
    col
    for col in [
        "track_id",
        "track_name",
        "artists",
        "album_name",
        "track_genre",
        "popularity",
        "explicit",
    ]
    if col in tracks_silver.columns
]
tracks_silver.select(metadata_cols).write.mode("overwrite").parquet(str(gold_tracks_local))

lyrics_metadata_cols = [
    col
    for col in [
        "track_id",
        "track_name",
        "artists",
        "album_name",
        "track_genre",
        "popularity",
        "explicit",
        "lyrics_length",
        "lyrics_word_count",
        "has_lyrics",
    ]
    if col in lyrics_silver.columns
]
lyrics_meta = lyrics_silver
if "track_genre" not in lyrics_meta.columns:
    lyrics_meta = lyrics_meta.withColumn("track_genre", F.lit("lyrics_dataset"))
if "popularity" not in lyrics_meta.columns:
    lyrics_meta = lyrics_meta.withColumn("popularity", F.lit(0))
if "explicit" not in lyrics_meta.columns:
    lyrics_meta = lyrics_meta.withColumn("explicit", F.lit(False))
lyrics_meta = lyrics_meta.withColumn("lyrics_length", F.length(F.coalesce(F.col("lyrics"), F.lit(""))))
lyrics_meta = lyrics_meta.withColumn("lyrics_word_count", F.size(F.split(F.trim(F.coalesce(F.col("lyrics"), F.lit(""))), r"\s+")))
lyrics_meta = lyrics_meta.withColumn("has_lyrics", (F.col("lyrics_length") > 0).cast("int"))
lyrics_metadata_cols = [c for c in ["track_id", "track_name", "artists", "album_name", "track_genre", "popularity", "explicit", "lyrics_length", "lyrics_word_count", "has_lyrics"] if c in lyrics_meta.columns]
lyrics_meta.select(lyrics_metadata_cols).write.mode("overwrite").parquet(str(gold_lyrics_local))

def upload_directory(local_dir: Path, bucket: str, prefix: str) -> None:
    for path in local_dir.rglob("*"):
        if path.is_file():
            rel = path.relative_to(local_dir).as_posix()
            key = f"{prefix}/{rel}"
            s3.upload_file(str(path), bucket, key)

upload_directory(gold_local, settings.bucket_name, "gold/mood_prepared")
upload_directory(tracks_local, settings.bucket_name, "gold/tracks_prepared")
upload_directory(lyrics_local, settings.bucket_name, "gold/lyrics_prepared")
upload_directory(gold_tracks_local, settings.bucket_name, "gold/tracks_dataset")
upload_directory(gold_lyrics_local, settings.bucket_name, "gold/lyrics_dataset")

print("Saved and uploaded to:")
print("-", f"s3://{settings.bucket_name}/gold/mood_prepared/train")
print("-", f"s3://{settings.bucket_name}/gold/mood_prepared/test")
print("-", f"s3://{settings.bucket_name}/gold/mood_prepared/scaler_stats")
print("-", f"s3://{settings.bucket_name}/gold/tracks_prepared/full")
print("-", f"s3://{settings.bucket_name}/gold/lyrics_prepared/full")
print("-", f"s3://{settings.bucket_name}/gold/tracks_dataset")
print("-", f"s3://{settings.bucket_name}/gold/lyrics_dataset")


# Registrar Gold en AWS Glue Data Catalog y validar con Athena.
gold_athena_specs = [
    AthenaTableSpec(
        table_name="gold_mood_prepared_train",
        s3_location=f"s3://{settings.bucket_name}/gold/mood_prepared/train/",
        local_path=train_local,
        description="Gold prepared training split for mood classifier",
    ),
    AthenaTableSpec(
        table_name="gold_mood_prepared_test",
        s3_location=f"s3://{settings.bucket_name}/gold/mood_prepared/test/",
        local_path=test_local,
        description="Gold prepared test split for mood classifier",
    ),
    AthenaTableSpec(
        table_name="gold_tracks_prepared_full",
        s3_location=f"s3://{settings.bucket_name}/gold/tracks_prepared/full/",
        local_path=tracks_out_local,
        description="Gold prepared tracks catalog for recommendation",
    ),
    AthenaTableSpec(
        table_name="gold_lyrics_prepared_full",
        s3_location=f"s3://{settings.bucket_name}/gold/lyrics_prepared/full/",
        local_path=lyrics_out_local,
        description="Gold prepared lyrics catalog for recommendation",
    ),
    AthenaTableSpec(
        table_name="gold_tracks_dataset",
        s3_location=f"s3://{settings.bucket_name}/gold/tracks_dataset/",
        local_path=gold_tracks_local,
        description="Gold tracks metadata",
    ),
    AthenaTableSpec(
        table_name="gold_lyrics_dataset",
        s3_location=f"s3://{settings.bucket_name}/gold/lyrics_dataset/",
        local_path=gold_lyrics_local,
        description="Gold lyrics metadata",
    ),
]
athena_tables = register_parquet_tables(settings, gold_athena_specs)
athena_results = run_validation_queries(settings, athena_tables)
print("Glue/Athena tables:", athena_tables)
print("Athena validation executions:", athena_results)

Saved and uploaded to:
- s3://music-recommender-lake-807744154206/gold/mood_prepared/train
- s3://music-recommender-lake-807744154206/gold/mood_prepared/test
- s3://music-recommender-lake-807744154206/gold/mood_prepared/scaler_stats
- s3://music-recommender-lake-807744154206/gold/tracks_prepared/full
- s3://music-recommender-lake-807744154206/gold/lyrics_prepared/full
- s3://music-recommender-lake-807744154206/gold/tracks_dataset
- s3://music-recommender-lake-807744154206/gold/lyrics_dataset
Glue/Athena tables: ['gold_mood_prepared_train', 'gold_mood_prepared_test', 'gold_tracks_prepared_full', 'gold_lyrics_prepared_full', 'gold_tracks_dataset', 'gold_lyrics_dataset']
Athena validation executions: {'gold_mood_prepared_train': '6028f33f-f0ef-40ff-87a4-9eacae6df6b0', 'gold_mood_prepared_test': 'fd28f337-82b2-4eff-bcbe-71c2555150ac', 'gold_tracks_prepared_full': '2d9dd492-3668-4762-880a-aec356779563', 'gold_lyrics_prepared_full': '97920b55-9afc-4d33-a291-1b48e8d49928', 'gold_tracks_dataset': 'acbfc914-42c0-45f4-a574-fbf425545ec6', 'gold_lyrics_dataset': '6027edf8-0564-48a9-932a-051270a638dc'}

## 9. Checklist de requisitos de preparacion

La siguiente tabla resume donde queda cubierto cada requisito formal de preparacion del conjunto de datos.

In [ ]:
prep_checklist = pd.DataFrame([
    ("Integracion de datos", "Cubierto", "Se descargan y leen mood, tracks y lyrics; se valida esquema comun y conflictos en 2.1."),
    ("Unificacion de multiples datasets", "Cubierto", "Se usa un esquema acustico comun y se generan salidas Gold separadas pero compatibles."),
    ("Tipos de datos", "Cubierto", "Casts explicitos a double/int antes de limpiar."),
    ("Duplicados", "Cubierto", "dropDuplicates en mood, tracks y lyrics; reporte previo en 2.1."),
    ("Conflictos entre fuentes", "Cubierto", "Reporte de conflictos de metadatos tracks vs lyrics y resolucion por fuente de confianza."),
    ("Variables irrelevantes", "Cubierto", "Seleccion por compatibilidad acustica y apoyo de correlacion en 2.2."),
    ("Valores faltantes", "Cubierto", "Se eliminan registros con valores faltantes"),
    ("Valores atipicos", "Cubierto", "Clipping IQR por feature numerica."),
    ("Discretizacion", "Cubierto", "Buckets low/mid/high de energy y valence."),
    ("Descomposicion", "No aplica", "No hay fechas utiles en estos datasets; letras se descomponen en longitud, palabras y tasas lexicas."),
    ("Transformaciones log/sqrt/x2", "Cubierto", "tempo_log1p, duration_sqrt, energy_squared."),
    ("Variables combinadas", "Cubierto", "energy_valence_interaction y acoustic_instrumental_mix."),
    ("Escalado", "Cubierto", "Estandarizacion z-score con estadisticas del train source mood."),
    ("Encoding categorico", "Cubierto", "One-hot manual de buckets energy/valence."),
    ("Split 80/20", "Cubierto", "Split estratificado por mood_label con randomSplit [0.8, 0.2]."),
], columns=["requisito", "estado", "evidencia"])
display(prep_checklist)

                            requisito     estado                                          evidencia
0                Integracion de datos   Cubierto  Se descargan y leen mood, tracks y lyrics; se ...
1   Unificacion de multiples datasets   Cubierto  Se usa un esquema acustico comun y se generan ...
2                      Tipos de datos   Cubierto    Casts explicitos a double/int antes de limpiar.
3                          Duplicados   Cubierto  dropDuplicates en mood, tracks y lyrics; repor...
4            Conflictos entre fuentes   Cubierto  Reporte de conflictos de metadatos tracks vs l...
5              Variables irrelevantes   Cubierto  Seleccion por compatibilidad acustica y apoyo ...
6                   Valores faltantes   Cubierto  Imputacion por mediana numerica y coalesce/tri...
7                    Valores atipicos   Cubierto                 Clipping IQR por feature numerica.
8                      Discretizacion   Cubierto          Buckets low/mid/high de energy y valence.
9                      Descomposicion  No aplica  No hay fechas utiles en estos datasets; letras...
10       Transformaciones log/sqrt/x2   Cubierto        tempo_log1p, duration_sqrt, energy_squared.
11               Variables combinadas   Cubierto  energy_valence_interaction y acoustic_instrume...
12                           Escalado   Cubierto  Estandarizacion z-score con estadisticas del t...
13                Encoding categorico   Cubierto          One-hot manual de buckets energy/valence.
14                        Split 80/20   Cubierto  Split estratificado por mood_label con randomS...